# Generated by Django 4.2.5 on 2023-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='cnpj',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=55),
        ),
    ]
