# Generated by Django 4.2.5 on 2023-09-18 12:33

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0002_alter_manufacturer_cnpj_alter_supplier_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
    ]
