# Generated by Django 4.2.5 on 2023-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0003_alter_manufacturer_cnpj_alter_supplier_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
    ]
