# Generated by Django 4.2.5 on 2023-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0005_alter_manufacturer_cnpj_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ncm_code',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
