# Generated by Django 4.2.5 on 2023-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0006_alter_material_material_code_alter_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
