# Generated by Django 4.2.5 on 2023-10-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0009_alter_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
