# Generated by Django 4.2.5 on 2023-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0015_alter_machine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='material',
        ),
        migrations.AddField(
            model_name='machine',
            name='material',
            field=models.ManyToManyField(to='cpq.material'),
        ),
    ]
