# Generated by Django 4.2.5 on 2023-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0016_remove_machine_material_machine_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
