# Generated by Django 4.2.5 on 2023-10-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0017_machine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpq.machine'),
        ),
    ]
